name: Update IPTV Source

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  update:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download IPTV sources
        run: |
          mkdir -p output

          curl -L https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv4.m3m3u -o fanmingming.m3u

          curl -L https://raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u -o yuechan.m3u

          curl -L https://iptv-org.github.io/iptv/countries/cn.m3u -o iptvorg.m3u

          cat fanmingming.m3u yuechan.m3u iptvorg.m3u > output/source.m3u

      - name: Commit update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update IPTV source" || exit 0
          git push
